name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Step to check out the repository code
      - uses: actions/checkout@v4

      # Step to set up the specified Node.js version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step to install dependencies
      - name: Install dependencies
        run: npm ci

      # Step to run linting (if applicable)
      - name: Lint code
        run: npm run lint --if-present

      # Step to run tests
      - name: Run tests
        env:
          PORT: 8080
        run: npm test

      # (Optional) Step to build the project
      - name: Build project
        run: npm run build --if-present
